### ISSUE TITLE
Fork Suricata Repository for Automated Code Review - SourceCloud

### ISSUE THREAD

**Issue by bbauwens** [UNO-CYBR-8420-Team1/CYBR8420-Suricata#27]

**Comment by shellis0** [comment]
**Current Progress:**
- Forked the Suricata repository to my account for automated code scanning with SonarCloud
- I setup a SonarCloud account using the free plan (for scanning public repositories and open-source projects)
- I attempted to integrate SonarCloud with GitHub Actions, but ultimately analyzed the open-source project through SonarCloud directly
- A report was successfully generated in SonarCloud.
- I will proceed to close the issue once I start adding the results of the SonarCloud analysis to our project deliverable
